userinput = input("Enter a string: ")
print(userinput [2])
print(userinput [-2])
print(userinput [:5])
print(userinput [:-2])
print(userinput [0::2])
print(userinput [1::2])
print(userinput [::-1])
print(userinput [::-2])
print(len(userinput))